### ISSUE TITLE
Tests Tracker

### ISSUE THREAD

**Issue by jeongY-Cho** [Pogify/pogify#51]
This issue tracks the files that need / have tests. 

- [ ] `/components`
    - [ ] `HostPlayer/index.jsx`
    - [ ] `ListenerPlayer/index.jsx`
    - [ ] `Player.jsx`
    - [ ] `utils/CopyLink.jsx`
    - [ ] `Donations.jsx`
    - [ ] `NewTabLink.jsx`
    - [ ] `PoweredBySpotify.jsx`
- [ ] `/layouts`
    - [ ] `Layout.jsx`
- [ ] `/modals`
    - [ ] `ErrorModal.jsx`
    - [ ] `ModalSystem.jsx`
    - [ ] `WarningModal.jsx`
- [ ] `/routes`
    - [ ] `AuthRedirect.jsx`
    - [ ] `ConnectToSession.jsx`
    - [ ] `Create.jsx`
    - [ ] `FourOhFour.jsx`
    - [ ] `Home.jsx`
    - [ ] `Privacy.jsx` 
    - [ ] `Room.jsx` 
    - [ ] `Terms.jsx`
- [ ] `/stores`
    - [x] `modalStore.js`
    - [ ] `playerStore.js`
    - [ ] `themeStore.js`
- [ ] `/utils`
    - [ ] `debounce.js`
    - [x] `formatters.js`
    - [ ] `sessionManager.js`
